openapi: "3.0.2"
info:
  title: CodenameDev
  version: "1.0"
servers:
  - url: https://localhost
paths:
  /time:
    get:
      tags:
        - getTime
      summary: Get the time
      description: ""
      responses:
        "200":
          description: OK
  /ask:
    post:
      tags:
        - ask
      summary: Dispatch the question
      description: ""
      operationId: questionDispatch
      parameters:
        - name: model
          in: query
          required: true
          schema:
            type: string
            default: "gpt-3.5-turbo"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  example: "user"
                content:
                  type: string
                  example: "echo my test message"
      responses:
        "200":
          description: OK
        "400":
          description: Invalid input
